"""Export for page-mascot, the cursor-tracking web component.

Kept out of `TARGETS` on purpose. Every other target takes one `Atlas` and an
fps and turns a motion loop into that platform's playback; this one takes two
atlases, has no fps, and means nothing unless the cells are the nine compass
directions and nine expressions the component expects. Putting it in `TARGETS`
would make an ordinary `mascotify ingest wave/sheet.png` emit a "directions"
sheet whose cells are nine arbitrary moments of a wave — a mascot that snaps its
head around at random as the cursor moves.

Upstream: https://github.com/nilbuild/page-mascot
"""

from __future__ import annotations

import re
from pathlib import Path

from ..imaging.pack import Atlas
from .targets import Bundle, _write

PACKAGE = "page-mascot"


def _component(name: str) -> str:
    """A job name as a JS identifier.

    `str.capitalize` was enough until a job was called `robot-wave`, which it
    turned into `Robot-waveMascot` — a name that does not compile.
    """
    parts = [p for p in re.split(r"[^0-9a-zA-Z]+", name) if p]
    ident = "".join(p[:1].upper() + p[1:] for p in parts) or "Mascot"
    return ident if not ident[0].isdigit() else f"M{ident}"


def _attr(text: str) -> str:
    """Escape for a JSX attribute. JSX decodes HTML entities in these, so a
    description containing a quote stays readable instead of ending the
    attribute early and breaking the file it is written into."""
    for raw, entity in (("&", "&amp;"), ('"', "&quot;"), ("<", "&lt;"), (">", "&gt;")):
        text = text.replace(raw, entity)
    return text


def _sheet(atlas: Atlas, path: Path) -> Path:
    """One still WebP, losslessly.

    Lossy WebP bleeds colour across block boundaries, and the component samples
    cells with `background-position` — so a lossy edge shows up at runtime as a
    sliver of the neighbouring pose down the side of the mascot. An animated
    preview never reveals this because the frames are moving; a grid that holds
    one cell still does.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    atlas.image.save(path, format="WEBP", lossless=True, method=6)
    return path


def export_page_mascot(
    directions: Atlas,
    reactions: Atlas,
    out: Path,
    name: str,
    *,
    base_px: int = 140,
    label: str = "",
) -> Bundle:
    """The two sheets the component loads, plus the JSX that mounts it."""
    root = out / PACKAGE
    root.mkdir(parents=True, exist_ok=True)

    dir_png = _sheet(directions, root / f"{name}-directions.webp")
    react_png = _sheet(reactions, root / f"{name}-reactions.webp")

    alt = label or f"{name} mascot"
    snippet = (
        "<Mascot\n"
        f'  directions="/mascots/{name}-directions.webp"\n'
        f'  reactions="/mascots/{name}-reactions.webp"\n'
        f"  size={{{base_px}}}\n"
        f'  label="{_attr(alt)}"\n'
        "/>"
    )

    usage = _write(
        root / f"{_component(name)}Mascot.tsx",
        f"""import {{ Mascot }} from '{PACKAGE}'

/**
 * {name}, a {directions.cols}x{directions.rows} direction grid and a matching
 * reaction grid. Generated by mascotify.
 *
 * Both sheets are seated on one shared body anchor, so the character does not
 * jump when a click swaps from the directions sheet to the reactions sheet.
 *
 * Copy the two .webp files into `public/mascots/`, or import them and pass the
 * resolved URLs — the props are whatever your app serves.
 */
export function {_component(name)}Mascot() {{
  return (
    {snippet.replace(chr(10), chr(10) + "    ")}
  )
}}
""",
    )

    return Bundle(
        target=PACKAGE,
        root=root,
        files=[dir_png, react_png, usage],
        snippet=snippet,
        install_hint=(
            f"npm i {PACKAGE}, then copy the two .webp files into public/mascots/. "
            "Tracking needs a fine pointer; the component sits still on touch."
        ),
    )
