"""Platform export bundles.

Each target writes the asset in the form that platform's tooling expects, plus
the smallest snippet that actually plays it. The snippet matters more than it
looks: a sprite sheet with no playback code is a puzzle, and every platform
solves it differently enough that guessing wastes an afternoon.
"""

from __future__ import annotations

import base64
import json
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path

from PIL import Image

from ..imaging.pack import Atlas, write_animation


@dataclass
class Bundle:
    """What an export produced and how to use it."""

    target: str
    root: Path
    files: list[Path]
    snippet: str
    install_hint: str = ""

    def rel(self) -> list[str]:
        return [str(p.relative_to(self.root)) for p in self.files]


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path


# --------------------------------------------------------------------------- web


def export_web(atlas: Atlas, frames: list[Image.Image], out: Path, name: str) -> Bundle:
    """Animated WebP plus a CSS `steps()` sheet.

    Both are shipped because they fail differently: the WebP is one tag and no
    CSS, but you cannot pause or scrub it; the sprite sheet is controllable and
    survives `prefers-reduced-motion`.
    """
    root = out / "web"
    root.mkdir(parents=True, exist_ok=True)
    webp = write_animation(frames, root / f"{name}.webp", fps=atlas.fps)
    sheet = root / f"{name}-sheet.png"
    atlas.image.save(sheet)

    duration = atlas.count / atlas.fps
    css = f""".{name} {{
  width: {atlas.cell_w}px;
  height: {atlas.cell_h}px;
  background-image: url("{name}-sheet.png");
  background-repeat: no-repeat;
  animation: {name}-play {duration:.3f}s steps(1) infinite;
}}

/* One keyframe per cell. steps(1) holds each frame rather than tweening
   between them, which is what makes a sprite sheet read as animation. */
@keyframes {name}-play {{
{chr(10).join(
    f"  {i / atlas.count * 100:.4f}% {{ background-position: "
    f"{-(i % atlas.cols) * atlas.cell_w}px {-(i // atlas.cols) * atlas.cell_h}px; }}"
    for i in range(atlas.count)
)}
}}

@media (prefers-reduced-motion: reduce) {{
  .{name} {{ animation: none; background-position: 0 0; }}
}}
"""
    css_path = _write(root / f"{name}.css", css)
    html = _write(
        root / "index.html",
        f"""<!doctype html>
<meta charset="utf-8">
<title>{name}</title>
<link rel="stylesheet" href="{name}.css">
<body style="display:grid;place-items:center;min-height:100vh;gap:2rem;background:#111">
  <div class="{name}"></div>
  <img src="{name}.webp" width="{atlas.cell_w}" height="{atlas.cell_h}" alt="{name}">
</body>
""",
    )
    return Bundle(
        target="web",
        root=root,
        files=[webp, sheet, css_path, html],
        snippet=f'<link rel="stylesheet" href="{name}.css">\n<div class="{name}"></div>',
    )


# --------------------------------------------------------------------------- iOS


def export_ios(atlas: Atlas, frames: list[Image.Image], out: Path, name: str, base_pt: int) -> Bundle:
    """An Xcode `.imageset` per frame, plus a SwiftUI view that plays them.

    Frames go in as individual images at @1x/@2x/@3x rather than as one sheet:
    UIImage.animatedImage wants an array, and slicing a sheet at runtime costs
    more than the extra files save.
    """
    root = out / "ios"
    assets = root / "Mascot.xcassets"
    files: list[Path] = []

    scale_for = {1: base_pt, 2: base_pt * 2, 3: base_pt * 3}
    for i, frame in enumerate(frames):
        imageset = assets / f"{name}{i}.imageset"
        imageset.mkdir(parents=True, exist_ok=True)
        images = []
        for scale, px in scale_for.items():
            fn = f"{name}{i}@{scale}x.png" if scale > 1 else f"{name}{i}.png"
            frame.resize((px, round(px * frame.height / frame.width)), Image.LANCZOS).save(
                imageset / fn
            )
            files.append(imageset / fn)
            images.append({"idiom": "universal", "filename": fn, "scale": f"{scale}x"})
        files.append(
            _write(
                imageset / "Contents.json",
                json.dumps({"images": images, "info": {"author": "mascotify", "version": 1}}, indent=2),
            )
        )

    files.append(
        _write(
            assets / "Contents.json",
            json.dumps({"info": {"author": "mascotify", "version": 1}}, indent=2),
        )
    )

    swift = _write(
        root / "MascotSprite.swift",
        f'''import SwiftUI

/// {name}, {atlas.count} frames at {atlas.fps} fps. Generated by mascotify.
public struct MascotSprite: View {{
    private static let frameCount = {atlas.count}
    private static let fps = {atlas.fps}

    @State private var index = 0
    private let timer = Timer.publish(
        every: 1.0 / Double(fps), on: .main, in: .common
    ).autoconnect()

    /// Honours Reduce Motion by holding on the first frame — an idle mascot is
    /// decorative, so animating through that setting is the wrong default.
    @Environment(\\.accessibilityReduceMotion) private var reduceMotion

    public init() {{}}

    public var body: some View {{
        Image("{name}\\(index)")
            .resizable()
            .scaledToFit()
            .frame(width: {base_pt})
            .onReceive(timer) {{ _ in
                guard !reduceMotion else {{ return }}
                index = (index + 1) % Self.frameCount
            }}
    }}
}}
''',
    )
    return Bundle(
        target="ios",
        root=root,
        files=files + [swift],
        snippet="MascotSprite()",
        install_hint="Drag Mascot.xcassets into your Xcode project, then add MascotSprite.swift.",
    )


# ----------------------------------------------------------------------- android


def export_android(atlas: Atlas, frames: list[Image.Image], out: Path, name: str) -> Bundle:
    """Animated WebP in `res/drawable`, played as an AnimatedImageDrawable.

    An `<animation-list>` of individual PNGs is the older route and inflates
    every frame as a separate drawable; one animated WebP decodes lazily.
    """
    root = out / "android"
    drawable = root / "res" / "drawable"
    webp = write_animation(frames, drawable / f"{name}.webp", fps=atlas.fps)

    kotlin = _write(
        root / f"{name.capitalize()}Mascot.kt",
        f'''import android.graphics.drawable.AnimatedImageDrawable
import android.widget.ImageView

/** {name}, {atlas.count} frames at {atlas.fps} fps. Generated by mascotify. */
fun ImageView.playMascot() {{
    setImageResource(R.drawable.{name})
    (drawable as? AnimatedImageDrawable)?.apply {{
        repeatCount = AnimatedImageDrawable.REPEAT_INFINITE
        start()
    }}
}}
''',
    )
    return Bundle(
        target="android",
        root=root,
        files=[webp, kotlin],
        snippet="mascotView.playMascot()",
        install_hint="AnimatedImageDrawable needs API 28+. Copy res/drawable into your module.",
    )


# -------------------------------------------------------------------------- Unity


def export_unity(atlas: Atlas, out: Path, name: str) -> Bundle:
    """Sprite sheet with the metadata Unity's slicer needs.

    Unity writes its own .meta on import, so shipping one risks a GUID clash.
    The sidecar records the grid instead and the snippet applies it.
    """
    root = out / "unity"
    root.mkdir(parents=True, exist_ok=True)
    sheet = root / f"{name}.png"
    atlas.image.save(sheet)
    meta = _write(root / f"{name}.slice.json", json.dumps(atlas.meta(name), indent=2) + "\n")

    snippet = _write(
        root / f"{name.capitalize()}Mascot.cs",
        f'''using UnityEngine;

// {name}, {atlas.count} frames at {atlas.fps} fps. Generated by mascotify.
// Import {name}.png as Sprite (2D and UI), Sprite Mode = Multiple, then slice
// by Cell Size {atlas.cell_w} x {atlas.cell_h}.
[RequireComponent(typeof(SpriteRenderer))]
public class {name.capitalize()}Mascot : MonoBehaviour
{{
    public Sprite[] frames;          // assign the sliced sub-sprites
    public float fps = {atlas.fps}f;

    SpriteRenderer _renderer;
    float _t;

    void Awake() => _renderer = GetComponent<SpriteRenderer>();

    void Update()
    {{
        if (frames == null || frames.Length == 0) return;
        _t += Time.deltaTime;
        _renderer.sprite = frames[(int)(_t * fps) % frames.Length];
    }}
}}
''',
    )
    return Bundle(
        target="unity",
        root=root,
        files=[sheet, meta, snippet],
        snippet=f"Slice {name}.png at cell size {atlas.cell_w}x{atlas.cell_h}.",
    )


# -------------------------------------------------------------------------- Godot


def export_godot(atlas: Atlas, out: Path, name: str) -> Bundle:
    """A SpriteFrames resource Godot 4 loads directly.

    AtlasTexture regions reference the one sheet, so the project carries a
    single image rather than N imported textures.
    """
    root = out / "godot"
    root.mkdir(parents=True, exist_ok=True)
    sheet = root / f"{name}.png"
    atlas.image.save(sheet)

    # Godot needs every sub-resource declared before the resource that uses them.
    subs = []
    refs = []
    for i in range(atlas.count):
        x, y, w, h = atlas.frame_rect(i)
        subs.append(
            f'[sub_resource type="AtlasTexture" id="frame_{i}"]\n'
            f'atlas = ExtResource("sheet")\n'
            f"region = Rect2({x}, {y}, {w}, {h})\n"
        )
        refs.append(f'{{ "duration": 1.0, "texture": SubResource("frame_{i}") }}')

    tres = _write(
        root / f"{name}_frames.tres",
        f"""[gd_resource type="SpriteFrames" load_steps={atlas.count + 2} format=3]

[ext_resource type="Texture2D" path="res://{name}.png" id="sheet"]

{chr(10).join(subs)}
[resource]
animations = [{{
"frames": [{", ".join(refs)}],
"loop": true,
"name": &"{name}",
"speed": {float(atlas.fps)}
}}]
""",
    )
    return Bundle(
        target="godot",
        root=root,
        files=[sheet, tres],
        snippet=f'$AnimatedSprite2D.sprite_frames = load("res://{name}_frames.tres")\n'
        f'$AnimatedSprite2D.play("{name}")',
    )


# ------------------------------------------------------------------------- Lottie


def export_lottie(atlas: Atlas, frames: list[Image.Image], out: Path, name: str) -> Bundle:
    """Lottie JSON with the frames embedded as base64 images.

    Genuinely a raster sequence wearing a Lottie wrapper — there are no vector
    paths to recover from a generated bitmap. Worth shipping anyway because it
    drops into an existing Lottie pipeline with no new dependency, but it will
    not scale like hand-authored Lottie and the file is large.
    """
    root = out / "lottie"
    root.mkdir(parents=True, exist_ok=True)
    w, h = atlas.cell_w, atlas.cell_h

    assets, layers = [], []
    for i, frame in enumerate(frames):
        buf = BytesIO()
        frame.save(buf, format="PNG", optimize=True)
        assets.append(
            {
                "id": f"image_{i}",
                "w": w,
                "h": h,
                "u": "",
                "p": "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode(),
                "e": 1,
            }
        )
        # Each frame is a layer visible for exactly one frame of the timeline.
        layers.append(
            {
                "ddd": 0,
                "ind": i + 1,
                "ty": 2,
                "nm": f"frame_{i}",
                "refId": f"image_{i}",
                "ks": {
                    "o": {"a": 0, "k": 100},
                    "r": {"a": 0, "k": 0},
                    "p": {"a": 0, "k": [w / 2, h / 2, 0]},
                    "a": {"a": 0, "k": [w / 2, h / 2, 0]},
                    "s": {"a": 0, "k": [100, 100, 100]},
                },
                "ao": 0,
                "ip": i,
                "op": i + 1,
                "st": 0,
                "bm": 0,
            }
        )

    doc = {
        "v": "5.7.4",
        "fr": atlas.fps,
        "ip": 0,
        "op": atlas.count,
        "w": w,
        "h": h,
        "nm": name,
        "ddd": 0,
        "assets": assets,
        "layers": list(reversed(layers)),
    }
    path = _write(root / f"{name}.json", json.dumps(doc, separators=(",", ":")))
    return Bundle(
        target="lottie",
        root=root,
        files=[path],
        snippet=f'<lottie-player src="{name}.json" autoplay loop></lottie-player>',
        install_hint="Raster frames in a Lottie container — it will not scale like vector Lottie.",
    )


TARGETS = ("web", "ios", "android", "unity", "godot", "lottie")


def export_all(
    atlas: Atlas,
    frames: list[Image.Image],
    out: Path,
    name: str,
    targets: tuple[str, ...] = TARGETS,
    base_pt: int = 120,
) -> list[Bundle]:
    bundles: list[Bundle] = []
    for t in targets:
        if t == "web":
            bundles.append(export_web(atlas, frames, out, name))
        elif t == "ios":
            bundles.append(export_ios(atlas, frames, out, name, base_pt))
        elif t == "android":
            bundles.append(export_android(atlas, frames, out, name))
        elif t == "unity":
            bundles.append(export_unity(atlas, out, name))
        elif t == "godot":
            bundles.append(export_godot(atlas, out, name))
        elif t == "lottie":
            bundles.append(export_lottie(atlas, frames, out, name))
        else:
            raise ValueError(f"unknown export target {t!r}; known: {', '.join(TARGETS)}")
    return bundles
